from enum import Enum


class StateStatusEnum(str, Enum):

    CREATED = 'CREATED'
    QUEUED = 'QUEUED'
    EXECUTED = 'EXECUTED'
    NEXT_CREATED = 'NEXT_CREATED'
    RETRY_CREATED = 'RETRY_CREATED'
    TIMEDOUT = 'TIMEDOUT'
    ERRORED = 'ERRORED'
    CANCELLED = 'CANCELLED'
    SUCCESS = 'SUCCESS'
    NEXT_CREATED_ERROR = 'NEXT_CREATED_ERROR'
